python test_mnist.py --model FC --n_hidden 1000 --epoch 0 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_0.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 10 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_10.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 20 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_20.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 30 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_30.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 40 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_40.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 50 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_50.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 60 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_60.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 70 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_70.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 80 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_80.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 90 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_90.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 100 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_100.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 110 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_110.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 120 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_120.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 130 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_130.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 140 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_140.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 150 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_150.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 160 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_160.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 170 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_170.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 180 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_180.txt
python test_mnist.py --model FC --n_hidden 1000 --epoch 190 > /vulcanscratch/songweig/logs/adv_pool/mnist_gd/mnist_FC_1000_190.txt
